import type { SidpDocument, UniversalDocument } from "./schema";

export const SAMPLE_EXTRACTED_DOC_1: UniversalDocument = {
  doc_type: "purchase_invoice",
  doc_type_confidence: 97,
  currency: "INR",
  header: {
    supplier_name: "Acme Textiles Pvt Ltd",
    supplier_address: "Plot 14, MIDC Industrial Area, Bhiwandi, Maharashtra",
    supplier_gstin: "27AAAFS5743E1ZA",
    supplier_pan: "AAAFS5743E",
    buyer_name: "Sakura Exports",
    buyer_gstin: "27AAAFS9988K1Z5",
    buyer_address: "Andheri East, Mumbai, Maharashtra",
    invoice_number: "INV-2201",
    invoice_date: "2026-08-04",
    po_number: "PO-0088",
    po_date: "2026-07-28",
    challan_number: null,
    vehicle_number: null,
    transporter_name: null,
    lr_number: null,
    eway_bill_number: "241100123456",
    payment_terms: "30 days from invoice date",
    bank_details: "HDFC Bank, A/C 5021xxxx1123, IFSC HDFC0000456",
    remarks: null,
    currency: "INR",
  },
  items: [
    {
      line_number: 1,
      item_code: "CTN-YRN-30",
      item_name: "Cotton Yarn 30s Combed",
      item_description: null,
      hsn_sac: "5205",
      batch_number: "B-2231",
      serial_number: null,
      brand: null,
      make: null,
      model: null,
      uom: "KG",
      quantity: 1200,
      free_quantity: 0,
      rate: 62.5,
      discount: 0,
      taxable_amount: 75000,
      cgst_percent: 2.5,
      cgst_amount: 1875,
      sgst_percent: 2.5,
      sgst_amount: 1875,
      igst_percent: null,
      igst_amount: null,
      cess: 0,
      line_total: 78750,
    },
    {
      line_number: 2,
      item_code: "CTN-YRN-40",
      item_name: "Cotton Yarn 40s Combed",
      item_description: null,
      hsn_sac: "5205",
      batch_number: "B-2232",
      serial_number: null,
      brand: null,
      make: null,
      model: null,
      uom: "KG",
      quantity: 80,
      free_quantity: 0,
      rate: 68,
      discount: 0,
      taxable_amount: 5440,
      cgst_percent: 2.5,
      cgst_amount: 136,
      sgst_percent: 2.5,
      sgst_amount: 136,
      igst_percent: null,
      igst_amount: null,
      cess: 0,
      line_total: 5712,
    },
  ],
  totals: {
    total_taxable: 80440,
    cgst: 2011,
    sgst: 2011,
    igst: null,
    cess: 0,
    freight: 0,
    insurance: 0,
    discount: 0,
    round_off: -0.62,
    grand_total: 84461,
  },
  detected_headers: [
    { source: "Nett Wt (Kg)", mapped_to: "quantity", confidence: 91 },
    { source: "Rate/Kg", mapped_to: "rate", confidence: 96 },
    { source: "Amt", mapped_to: "line_total", confidence: 88 },
  ],
  corrections: [{ field: "items[0].hsn_sac", from: "52O5", to: "5205", reason: "OCR confusion O→0 in HSN code" }],
  notes: [],
};

// Stand-in data so the UI can be built and reviewed before the Apps Script
// backend is deployed. Swap for api.listDocuments() once the Web App is live.
export const SAMPLE_DOCUMENTS: SidpDocument[] = [
  {
    id: "doc_1",
    user_id: "ritesh@sakuraexports.example",
    file_name: "Acme_Textiles_INV_2201.pdf",
    mime_type: "application/pdf",
    drive_file_id: "drive_1",
    status: "review",
    error_message: null,
    vendor_id: "vendor_1",
    extracted: SAMPLE_EXTRACTED_DOC_1,
    field_confidence: {
      "header.supplier_name": 99,
      "header.supplier_gstin": 97,
      "header.invoice_number": 99,
      "header.invoice_date": 94,
      "header.po_number": 91,
      "header.eway_bill_number": 82,
      "items[0].hsn_sac": 74,
      "items[0].quantity": 91,
      "items[0].rate": 96,
      "items[1].quantity": 96,
      "items[1].rate": 97,
      "totals.grand_total": 99,
    },
    validation: { issues: [{ severity: "info", field: "totals.round_off", message: "₹0.62 round-off applied automatically to reconcile line items with the printed grand total." }], score: 96 },
    rate_changes: [],
    edit_history: [],
    overall_confidence: 92,
    created_at: "2026-08-06T09:12:00Z",
    updated_at: "2026-08-06T09:14:00Z",
    doc_type: "purchase_invoice",
    doc_type_confidence: 97,
    invoice_number: "INV-2201",
    invoice_date: "2026-08-04",
    supplier_name: "Acme Textiles Pvt Ltd",
    supplier_gstin: "27AAAFS5743E1ZA",
    po_number: "PO-0088",
    challan_number: null,
    vehicle_number: null,
    grand_total: 84461,
    deleted_at: null,
  },
  {
    id: "doc_2",
    user_id: "ritesh@sakuraexports.example",
    file_name: "Ralco_PO_0098.pdf",
    mime_type: "application/pdf",
    drive_file_id: "drive_2",
    status: "processing",
    error_message: null,
    vendor_id: "vendor_2",
    extracted: null,
    field_confidence: {},
    validation: null,
    rate_changes: [],
    edit_history: [],
    overall_confidence: null,
    created_at: "2026-08-07T07:40:00Z",
    updated_at: "2026-08-07T07:40:00Z",
    doc_type: null,
    doc_type_confidence: null,
    invoice_number: null,
    invoice_date: null,
    supplier_name: "Ralco Industries",
    supplier_gstin: null,
    po_number: "PO-0098",
    challan_number: null,
    vehicle_number: null,
    grand_total: null,
    deleted_at: null,
  },
  {
    id: "doc_3",
    user_id: "ritesh@sakuraexports.example",
    file_name: "Vishal_Traders_Challan_331.jpg",
    mime_type: "image/jpeg",
    drive_file_id: "drive_3",
    status: "approved",
    error_message: null,
    vendor_id: "vendor_3",
    extracted: null,
    field_confidence: {},
    validation: { issues: [], score: 100 },
    rate_changes: [],
    edit_history: [],
    overall_confidence: 98,
    created_at: "2026-08-05T11:02:00Z",
    updated_at: "2026-08-05T11:20:00Z",
    doc_type: "delivery_challan",
    doc_type_confidence: 99,
    invoice_number: null,
    invoice_date: "2026-08-05",
    supplier_name: "Vishal Traders",
    supplier_gstin: "24AAACV1234F1Z2",
    po_number: null,
    challan_number: "DC-331",
    vehicle_number: "GJ-01-AB-4521",
    grand_total: 15600,
    deleted_at: null,
  },
  {
    id: "doc_4",
    user_id: "ritesh@sakuraexports.example",
    file_name: "Unreadable_Scan_009.pdf",
    mime_type: "application/pdf",
    drive_file_id: "drive_4",
    status: "failed",
    error_message: "Vision model returned low-confidence classification for all fields.",
    vendor_id: null,
    extracted: null,
    field_confidence: {},
    validation: null,
    rate_changes: [],
    edit_history: [],
    overall_confidence: 41,
    created_at: "2026-08-06T15:00:00Z",
    updated_at: "2026-08-06T15:01:00Z",
    doc_type: "other",
    doc_type_confidence: 41,
    invoice_number: null,
    invoice_date: null,
    supplier_name: null,
    supplier_gstin: null,
    po_number: null,
    challan_number: null,
    vehicle_number: null,
    grand_total: null,
    deleted_at: null,
  },
];
